--Query 1 - Get strike, ball, and hit percentage for a game
SELECT b.gameID, b.pitchball as BallPercentage, s.pitchstrike as StrikePercentage, p.pitchhit as HitPercentage
FROM GAME_PITCH_BALL_PERCENTAGE b, GAME_PITCH_STRIKE_PERCENTAGE s, GAME_HIT_PERCENTAGE p
WHERE b.gameID = s.gameID;

--Query 2 - Get a pitchers stats for the inning
SELECT b.*, s.*
FROM inning_balls_pitchtype b, inning_strikes_pitchtype s
WHERE b.gameID = s.gameID AND b.inningID = s.inningID;

--Query 3 - Which inning in a game has the highest ball percentage
SELECT gameID as GAME, inningID as INNING, pitchball as BallPercentage
FROM inning_pitch_ball_percentage
WHERE pitchball >= ALL (SELECT pitchball from INNING_PITCH_BALL_PERCENTAGE);

-- GET GAME THAT HAS THE MOST STRIKES FOR FASTBALLS
SELECT GAMEID, STRIKESPERFASTBALL
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERFASTBALL> ALL (
    SELECT STRIKESPERFASTBALL
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);
    
-- GET GAME THAT HAS THE MOST STRIKES FOR CURVEBALLS
SELECT GAMEID, STRIKESPERCURVEBALL
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERCURVEBALL> ALL (
    SELECT STRIKESPERCURVEBALL
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);
    
-- GET GAME THAT HAS THE MOST STRIKES FOR CUTTERS
SELECT GAMEID, STRIKESPERCUTTER
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERCUTTER> ALL (
    SELECT STRIKESPERCUTTER
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);
    
-- GET GAME THAT HAS THE MOST STRIKES FOR SLIDERS
SELECT GAMEID, STRIKESPERSLIDER
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERSLIDER> ALL (
    SELECT STRIKESPERSLIDER
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);
    
-- GET GAME THAT HAS THE MOST STRIKES FOR CHANGEUPS
SELECT GAMEID, STRIKESPERCHANGEUP
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERCHANGEUP> ALL (
    SELECT STRIKESPERCHANGEUP
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);
    
-- GET GAME THAT HAS THE MOST STRIKES FOR SPLITTERS
SELECT GAMEID, STRIKESPERSPLITTER
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERSPLITTER> ALL (
    SELECT STRIKESPERSPLITTER
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);