-- GET GAME THAT HAS THE MOST STRIKES FOR FASTBALLS
SELECT GAMEID, STRIKESPERFASTBALL
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERFASTBALL> ALL (
    SELECT STRIKESPERFASTBALL
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);
    
-- GET GAME THAT HAS THE MOST STRIKES FOR CURVEBALLS
SELECT GAMEID, STRIKESPERCURVEBALL
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERCURVEBALL> ALL (
    SELECT STRIKESPERCURVEBALL
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);
    
-- GET GAME THAT HAS THE MOST STRIKES FOR CUTTERS
SELECT GAMEID, STRIKESPERCUTTER
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERCUTTER> ALL (
    SELECT STRIKESPERCUTTER
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);
    
-- GET GAME THAT HAS THE MOST STRIKES FOR SLIDERS
SELECT GAMEID, STRIKESPERSLIDER
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERSLIDER> ALL (
    SELECT STRIKESPERSLIDER
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);
    
-- GET GAME THAT HAS THE MOST STRIKES FOR CHANGEUPS
SELECT GAMEID, STRIKESPERCHANGEUP
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERCHANGEUP> ALL (
    SELECT STRIKESPERCHANGEUP
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);
    
-- GET GAME THAT HAS THE MOST STRIKES FOR SPLITTERS
SELECT GAMEID, STRIKESPERSPLITTER
FROM GAME_STRIKES_PITCHTYPE G1
WHERE G1.STRIKESPERSPLITTER> ALL (
    SELECT STRIKESPERSPLITTER
    FROM GAME_STRIKES_PITCHTYPE G2
    WHERE G2.GAMEID <> G1.GAMEID);